// <auto-generated />
using System;
using FINAL_INTERN.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FINAL_INTERN.Data.Migrations
{
    [DbContext(typeof(finalInternDbContext))]
    partial class finalInternDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Alt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("alt");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("img");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResetPasswordToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("resetPasswordToken");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime")
                        .HasColumnName("resetTokenExpiry");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Accounts__3214EC270215FF01");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.CarInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("alt");

                    b.Property<int>("CategoriesOfCarId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriesOfCar_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Img")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("img");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("StockQuantit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Transmission")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Years")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__CarInfos__3214EC278791B85C");

                    b.HasIndex("CategoriesOfCarId");

                    b.ToTable("CarInfos");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.CategoriesOfCar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC27B4BDA787");

                    b.ToTable("CategoriesOfCar");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("Account_ID");

                    b.Property<DateTime?>("Dates")
                        .HasColumnType("datetime")
                        .HasColumnName("dates");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("NameOfCustomer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC273B98EC5C");

                    b.HasIndex("AccountId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("Account_ID");

                    b.Property<int>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("Car_ID");

                    b.Property<string>("NameOfCar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_ID");

                    b.Property<int?>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<double?>("Total")
                        .HasColumnType("float")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__OrderDet__3214EC275E303269");

                    b.HasIndex("AccountId");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("Account_ID");

                    b.Property<int?>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<int?>("CarId")
                        .HasColumnType("int")
                        .HasColumnName("Car_ID");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_ID");

                    b.Property<string>("PaymentCreatedAt")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_created_at");

                    b.Property<string>("PaymentsStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payments_status");

                    b.Property<int?>("VnpAmount")
                        .HasColumnType("int")
                        .HasColumnName("vnp_Amount");

                    b.Property<string>("VnpBankCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_BankCode");

                    b.Property<string>("VnpBankTranNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_BankTranNo");

                    b.Property<string>("VnpCartType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_CartType");

                    b.Property<string>("VnpOrderInfo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_OrderInfo");

                    b.Property<string>("VnpPayDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("vnp_PayDate");

                    b.Property<string>("VnpResponseCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_ResponseCode");

                    b.Property<string>("VnpTmnCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_TmnCode");

                    b.Property<string>("VnpTransactionNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_TransactionNo");

                    b.Property<string>("VnpTransactionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_TransactionStatus");

                    b.Property<string>("VnpTxnRef")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vnp_TxnRef");

                    b.HasKey("Id")
                        .HasName("PK__Payments__3214EC27AA80C635");

                    b.HasIndex("AccountId");

                    b.HasIndex("CarId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("NameOfRole")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC27D53A553F");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("Account_ID");

                    b.Property<string>("DayOfTransaction")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("day_of_transaction");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_ID");

                    b.Property<double?>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<double?>("Total")
                        .HasColumnType("float")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__Transact__3214EC27CAF24BFF");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Account", b =>
                {
                    b.HasOne("FINAL_INTERN.Models.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Accounts__resetT__398D8EEE");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.CarInfo", b =>
                {
                    b.HasOne("FINAL_INTERN.Models.Models.CategoriesOfCar", "CategoriesOfCar")
                        .WithMany("CarInfos")
                        .HasForeignKey("CategoriesOfCarId")
                        .IsRequired()
                        .HasConstraintName("FK__CarInfos__Catego__3F466844");

                    b.Navigation("CategoriesOfCar");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Order", b =>
                {
                    b.HasOne("FINAL_INTERN.Models.Models.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__Account___4222D4EF");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.OrderDetail", b =>
                {
                    b.HasOne("FINAL_INTERN.Models.Models.Account", "Account")
                        .WithMany("OrderDetails")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Accou__45F365D3");

                    b.HasOne("FINAL_INTERN.Models.Models.CarInfo", "Car")
                        .WithMany("OrderDetails")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Car_I__46E78A0C");

                    b.HasOne("FINAL_INTERN.Models.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderDeta__Order__44FF419A");

                    b.Navigation("Account");

                    b.Navigation("Car");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Payment", b =>
                {
                    b.HasOne("FINAL_INTERN.Models.Models.Account", "Account")
                        .WithMany("Payments")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Payments__Accoun__4AB81AF0");

                    b.HasOne("FINAL_INTERN.Models.Models.CarInfo", "Car")
                        .WithMany("Payments")
                        .HasForeignKey("CarId")
                        .HasConstraintName("FK__Payments__Car_ID__49C3F6B7");

                    b.HasOne("FINAL_INTERN.Models.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Payments__Order___4BAC3F29");

                    b.Navigation("Account");

                    b.Navigation("Car");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Transaction", b =>
                {
                    b.HasOne("FINAL_INTERN.Models.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Transacti__Accou__4E88ABD4");

                    b.HasOne("FINAL_INTERN.Models.Models.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Transacti__Order__4F7CD00D");

                    b.Navigation("Account");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Account", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.CarInfo", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.CategoriesOfCar", b =>
                {
                    b.Navigation("CarInfos");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FINAL_INTERN.Models.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
