// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FINAL_INTERN.Models.Models;

public partial class finalInternDbContext : DbContext
{
    public finalInternDbContext(DbContextOptions<finalInternDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<CarInfo> CarInfos { get; set; }

    public virtual DbSet<CategoriesOfCar> CategoriesOfCars { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Accounts__3214EC270215FF01");

            entity.HasOne(d => d.Role).WithMany(p => p.Accounts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Accounts__resetT__398D8EEE");
        });

        modelBuilder.Entity<CarInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CarInfos__3214EC278791B85C");

            entity.Property(e => e.StockQuantit).HasDefaultValue(5);

            entity.HasOne(d => d.CategoriesOfCar).WithMany(p => p.CarInfos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CarInfos__Catego__3F466844");
        });

        modelBuilder.Entity<CategoriesOfCar>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC27B4BDA787");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Orders__3214EC273B98EC5C");

            entity.HasOne(d => d.Account).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__Account___4222D4EF");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderDet__3214EC275E303269");

            entity.HasOne(d => d.Account).WithMany(p => p.OrderDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Accou__45F365D3");

            entity.HasOne(d => d.Car).WithMany(p => p.OrderDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Car_I__46E78A0C");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Order__44FF419A");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payments__3214EC27AA80C635");

            entity.HasOne(d => d.Account).WithMany(p => p.Payments).HasConstraintName("FK__Payments__Accoun__4AB81AF0");

            entity.HasOne(d => d.Car).WithMany(p => p.Payments).HasConstraintName("FK__Payments__Car_ID__49C3F6B7");

            entity.HasOne(d => d.Order).WithMany(p => p.Payments).HasConstraintName("FK__Payments__Order___4BAC3F29");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC27D53A553F");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Transact__3214EC27CAF24BFF");

            entity.HasOne(d => d.Account).WithMany(p => p.Transactions).HasConstraintName("FK__Transacti__Accou__4E88ABD4");

            entity.HasOne(d => d.Order).WithMany(p => p.Transactions).HasConstraintName("FK__Transacti__Order__4F7CD00D");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}