// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FINAL_INTERN.Models.Models;

public partial class Payment
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("Car_ID")]
    public int? CarId { get; set; }

    [Column("Account_ID")]
    public int? AccountId { get; set; }

    [Column("amount")]
    public int? Amount { get; set; }

    [Column("Order_ID")]
    public int? OrderId { get; set; }

    [Column("vnp_BankTranNo")]
    [StringLength(50)]
    public string VnpBankTranNo { get; set; }

    [Column("vnp_CartType")]
    [StringLength(50)]
    public string VnpCartType { get; set; }

    [Column("vnp_BankCode")]
    [StringLength(50)]
    public string VnpBankCode { get; set; }

    [Column("vnp_Amount")]
    public int? VnpAmount { get; set; }

    [Column("vnp_TxnRef")]
    [StringLength(50)]
    public string VnpTxnRef { get; set; }

    [Column("vnp_OrderInfo")]
    [StringLength(50)]
    public string VnpOrderInfo { get; set; }

    [Column("vnp_ResponseCode")]
    [StringLength(50)]
    public string VnpResponseCode { get; set; }

    [Column("vnp_TransactionNo")]
    [StringLength(50)]
    public string VnpTransactionNo { get; set; }

    [Column("vnp_TransactionStatus")]
    [StringLength(50)]
    public string VnpTransactionStatus { get; set; }

    [Column("vnp_PayDate")]
    [StringLength(50)]
    [Unicode(false)]
    public string VnpPayDate { get; set; }

    [Column("vnp_TmnCode")]
    [StringLength(50)]
    public string VnpTmnCode { get; set; }

    [Column("payment_created_at")]
    [StringLength(50)]
    [Unicode(false)]
    public string PaymentCreatedAt { get; set; }

    [Column("payments_status")]
    [StringLength(50)]
    public string PaymentsStatus { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Payments")]
    public virtual Account Account { get; set; }

    [ForeignKey("CarId")]
    [InverseProperty("Payments")]
    public virtual CarInfo Car { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Payments")]
    public virtual Order Order { get; set; }
}