// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FINAL_INTERN.Models.Models;

public partial class Transaction
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("day_of_transaction")]
    [StringLength(50)]
    [Unicode(false)]
    public string DayOfTransaction { get; set; }

    [Column("Account_ID")]
    public int? AccountId { get; set; }

    [Column("Order_ID")]
    public int? OrderId { get; set; }

    [Column("price")]
    public double? Price { get; set; }

    [Column("total")]
    public double? Total { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("Transactions")]
    public virtual Account Account { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Transactions")]
    public virtual Order Order { get; set; }
}